version: "3.8"

services:
  eggmorning-mysql:
    image: eggmorning-mysql
    restart: always
    ports:
      - 9306:3306
    environment:
      MYSQL_ROOT_PASSWORD: fJU8Cx.Hcce9
      MYSQL_USER: eggmorning
      MYSQL_PASSWORD: eggmorning-pw
      MYSQL_DATABASE: eggmorning
  eggmorning-spring-boot:
    image: adoptopenjdk:11
    command: sh -c "chmod u+x ./gradlew && ./gradlew clean build -xtest && java -jar ./build/libs/sommos-0.0.1-SNAPSHOT.jar"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app