version: "3.8"

services:
  eggmorning-mysql:
    image: eggmorning-mysql
    restart: always
    ports:
      - 9306:3306
    environment:
      MYSQL_ROOT_PASSWORD: fJU8Cx.Hcce9s
      MYSQL_USER: eggmorning
      MYSQL_PASSWORD: eggmorning-pw
      MYSQL_DATABASE: eggmorning
      LC_ALL: C.UTF-8
      TZ: Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  eggmorning-spring-boot:
    image: adoptopenjdk:11
    command: sh -c "chmod u+x ./gradlew && ./gradlew clean build -xtest -Pprofile=docker && java -Dspring.profiles.active=docker -jar ./build/libs/eggmorning-0.0.1-SNAPSHOT.jar"
    ports:
      - 8090:8080
    working_dir: /app
    volumes:
      - ../../:/app